---
output:

  html_document:
title: "Defence Analytics"
runtime: shiny

---
  
  
```{r setup, include=FALSE}

library(tidyverse)
library(lubridate)
library(httr)
library(RCurl)
library(jsonlite)
library(readxl)
library(dplyr)
library(shiny)
library(rmarkdown)
library(knitr)
library(tibble)
library(highcharter)
library(scales)

#setwd("/srv/shiny-server/RugbyAnalytics")

locale <- Sys.setlocale(category = "LC_ALL", locale = "C") 

####### 

####### Read in data


stadeplayerbase <- as.data.frame(readRDS(file = "stadeplayerbase.RDS"))
stadeplayerbase$Names <- trimws(stadeplayerbase$Names)



stadeplayerbase$week <- as.character(stadeplayerbase$week)
week <- as.data.frame(as.character(1:13))
names(week) <- "week"
stadeplayerbase$TacklesPerMin <- stadeplayerbase$Tackles/stadeplayerbase$Mins*80
stadeplayerbase$TacklesPercentage <- stadeplayerbase$Tackles/(stadeplayerbase$Tackles +stadeplayerbase$MissedTackles)
stadeplayerbase <- stadeplayerbase[order(stadeplayerbase$Names),]


stadeplayertotals <- as.data.frame(readRDS(file = "stadeplayertotals.RDS"))
stadeplayertotals$Names <- trimws(stadeplayertotals$Names)

stadeplayertable <- as.data.frame(readRDS(file = "stadeplayertable.RDS"))
####
#playerstats <- as.data.frame(readRDS(file = "playerstats.RDS"))

#stadeplayertotals <- left_join(stadeplayertotals, playerstats, by = "Names")
####



# stadeplayertotals <- stadeplayertotals %>%
#   group_by(Names) %>%
#   summarise("Tackles" = mean(Tackles, na.rm = TRUE), "Competition Average" = mean(Tackles.CompetitionTAverage), "Position Average" =mean(Tackles.CompetitionAverage.Position))




# stadeplayertotals$TacklesPercentage <- stadeplayertotals$Tackles/(stadeplayertotals$Tackles+stadeplayertotals$MissedTackles)






# this is missing , mean(Tackles.TeamAverage)
cols <- c('#f442eb' , '#f8bbd0', '#00BFFF', '#00008B')



```

<style type="text/css">

h1.title {
  font-size: 38px;
  text-align: center;
}

<!-- .col2 { -->
<!--     columns: 2 200px;         /* number of columns and width in pixels*/ -->
<!--     -webkit-columns: 2 200px; /* chrome, safari */ -->
<!--     -moz-columns: 2 200px;    /* firefox */ -->
<!--   } -->


</style>

<center>


</br>





```{r, echo = FALSE, fig.align="center"}
                              
selectInput("player", "Choose Player:",
            
            
            
            stadeplayerbase %>% distinct(Names))

       
```
  
  

<!-- ```{r, echo = FALSE, fig.align="center"} -->


<!-- t1 <- renderTable({ -->

<!--   x <- data.frame(c( -->
<!--   stadeplayertotals %>% -->
<!--     filter(Names ==  paste(input$player)) %>% -->
<!--     select("Position" = Position, "Nationality" = Country, "Date Of Birth" = DOB,"Heigh and Weight" = HeightWeight,"Joined Stade France" = Arrived) -->
<!-- )) -->
<!--   n <- x$name -->
<!--   x <- as.data.frame(t(x[,-1])) -->
<!--   colnames(x) <- n -->
<!--   x$myfactor <- factor(row.names(x)) -->
<!--   (x[,c(2,1)] -->

<!-- )}, -->
<!--                                     colnames=FALSE, -->
<!--                                     rownames =FALSE, -->
<!--                                     width= "600px"#, -->
<!--                                     #spacing= "l" -->
<!-- ) -->


<!-- t1 -->
<!-- ``` -->


```{r, echo = FALSE, fig.align="center"}


t2 <- renderTable({

  x <- data.frame(c(
  stadeplayertable %>%
    filter(Names ==   paste(input$player)) %>%
    select("Week" = week, "Played" = Played,"Winner" = Winner, "Opposition Score" = OppositionScore, "Position" = Position, "Mins" = Mins, "Tackles" = Tackles, "MissedTackles" = MissedTackles, "Turnovers" = Turnovers)%>%
    arrange(Week)
)) 
  
  x <- as.data.frame(t(x))
  # n <- x$week
  # colnames(x) <- n
  # x$myfactor <- factor(row.names(x))
  # (x[,c(2,1)]
  #   )

}

,
                                    colnames=FALSE,
                                    rownames =TRUE
                                    #width= "600px"#,
                                    #spacing= "l"
)


t2
```



***


</center>

<center>
<div class="row">
  <div class="col-md-6">



```{r, echo=FALSE, warning=FALSE}



p1 <- renderHighchart({



target <- stadeplayerbase %>% filter(Names == paste(input$player))

target <- target %>% select(week, TacklesPerMin, TacklesPerMin.TeamAverage, TacklesPerMin.CompetitionAverage, TacklesPerMin.CompetitionAverage.Position)


target <- left_join(week, target, by = "week")

highchart() %>% 
              hc_xAxis(categories = target$week) %>% 
              hc_add_series(name = "Tackles", data = target$TacklesPerMin, type = "column") %>%
              hc_add_series(name = "Team Average", data = target$TacklesPerMin.TeamAverage)  %>%
              hc_add_series(name = "Competition Average", data = target$TacklesPerMin.CompetitionAverage) %>%
              hc_add_series(name = "Position Average", data = target$TacklesPerMin.CompetitionAverage.Position ) %>%
                  hc_tooltip(sort = TRUE, table = TRUE, valueDecimals = 2) %>%
                  hc_colors(cols) %>%
                          hc_title(text = "Weighted Tackles Per Game")

# %>%
#   hc_tooltip(sort = TRUE, table = TRUE, valueDecimals = 2) %>%
#   hc_yAxis(min = 0, max = 1) %>%
#   hc_colors(cols)


})

p1
```


</div>
  <div class="col-md-6">



```{r, echo=FALSE, warning=FALSE}



pt4 <- renderHighchart({



target <- stadeplayertotals %>% filter(Names == paste(input$player))

highchart() %>%

              hc_add_series(name = "Tackles", data = target$TacklesWeighted, type = "column") %>%
              hc_add_series(name = "Team Average", data = target$TacklesPerMin.TeamAverage, type = "column") %>%
              hc_add_series(name = "Competition Average", data = target$TacklesPerMin.CompetitionAverage, type = "column") %>%
              hc_add_series(name = "Position Average", data = target$TacklesPerMin.CompetitionAverage.Position, type = "column") %>%
                  hc_tooltip(sort = TRUE, table = TRUE, valueDecimals = 2, type = "column") %>%
                  hc_colors(cols) %>%
                          hc_title(text = "Total Weighted Tackles per game")

# %>%
#   hc_tooltip(sort = TRUE, table = TRUE, valueDecimals = 2) %>%
#   hc_yAxis(min = 0, max = 1) %>%
#   hc_colors(cols)


})

pt4
```


</div>
</div>
<div class="row">
  <div class="col-md-6">



```{r, echo=FALSE, warning=FALSE}



p2 <- renderHighchart({



target <- stadeplayerbase %>% filter(Names == paste(input$player))

target <- target %>% select(week, TacklesPercentage, TacklePercentage.TeamAverage, TacklePercentage.CompetitionAverage, TacklePercentage.CompetitionAverage.Position)


target <- left_join(week, target, by = "week")
# 
# target$TacklesPercentage <- percent(target$TacklesPercentage)
# target$TacklePercentage.TeamAverage <- percent(target$TacklePercentage.TeamAverage)
# target$TacklePercentage.CompetitionAverage <- percent(target$TacklePercentage.CompetitionAverage)
# target$TacklePercentage.CompetitionAverage.Position <- percent(target$TacklePercentage.CompetitionAverage.Position) 

highchart() %>% 
  hc_title(text = "Tackle Percentage")%>%
              hc_xAxis(categories = target$week) %>% 
      hc_add_series(name = "Tackle %", data = target$TacklesPercentage, type = "column") %>%
      hc_add_series(name = "Team Average", data = target$TacklePercentage.TeamAverage) %>%
      hc_add_series(name = "Competition Average", data = target$TacklePercentage.CompetitionAverage) %>%
      hc_add_series(name = "Position Average", data = target$TacklePercentage.CompetitionAverage.Position) %>%
          hc_tooltip(sort = TRUE, table = TRUE, valueDecimals = 2) %>%
          hc_colors(cols) %>%
          hc_yAxis(min = .5, max = 1)
            
# %>%
#   hc_tooltip(sort = TRUE, table = TRUE, valueDecimals = 2) %>%

#   hc_colors(cols)


})

p2
```



</div>
  <div class="col-md-6">

```{r, echo=FALSE, warning=FALSE}



pt5 <- renderHighchart({



target <- stadeplayertotals %>% filter(Names == paste(input$player))


target <- stadeplayertotals %>% filter(Names == paste(input$player))

highchart() %>%

              hc_add_series(name = "Tackles", data = target$TacklePercentage, type = "column") %>%
              hc_add_series(name = "Team Average", data = target$TacklePercentage.TeamAverage, type = "column") %>%
              hc_add_series(name = "Competition Average", data = target$TacklePercentage.CompetitionAverage, type = "column") %>%
              hc_add_series(name = "Position Average", data = target$TacklePercentage.CompetitionAverage.Position, type = "column") %>%
                  hc_tooltip(sort = TRUE, table = TRUE, valueDecimals = 2, type = "column") %>%
                  hc_colors(cols) %>%
                          hc_title(text = "Total Tackle Percentage")%>%
                          hc_yAxis(min = .5, max = 1)

# %>%
#   hc_tooltip(sort = TRUE, table = TRUE, valueDecimals = 2) %>%
#   hc_yAxis(min = 0, max = 1) %>%
#   hc_colors(cols)


})

pt5
```


  </div>

</div>

<div class="row">
  <div class="col-md-6">


```{r, echo=FALSE, warning=FALSE}



p3 <- renderHighchart({



target <- stadeplayerbase %>% filter(Names == paste(input$player))

target <- target %>% select(week, Tackles, Tackles.TeamAverage, Tackles.CompetitionAverage, Tackles.CompetitionAverage.Position)


target <- left_join(week, target, by = "week")

highchart() %>% 
              hc_xAxis(categories = target$week) %>% 
      hc_add_series(name = "Tackles", data = target$Tackles, type = "column") %>%
      hc_add_series(name = "Team Average", data = target$Tackles.TeamAverage) %>%
      hc_add_series(name = "Competition Average", data = target$Tackles.CompetitionAverage) %>%
      hc_add_series(name = "Position Average", data = target$Tackles.CompetitionAverage.Position) %>%
          hc_tooltip(sort = TRUE, table = TRUE, valueDecimals = 2) %>%
          hc_colors(cols)%>%
          hc_title(text = "Average Tackles per game")
            
# %>%
#   hc_tooltip(sort = TRUE, table = TRUE, valueDecimals = 2) %>%
#   hc_yAxis(min = 0, max = 1) %>%
#   hc_colors(cols)


})

p3
```



  </div>
  <div class="col-md-6">




```{r, echo=FALSE, warning=FALSE}



pt6 <- renderHighchart({



target <- stadeplayertotals %>% filter(Names == paste(input$player))


target <- stadeplayertotals %>% filter(Names == paste(input$player))

highchart() %>%

              hc_add_series(name = "Tackles", data = target$Tackles, type = "column") %>%
              hc_add_series(name = "Team Average", data = target$Tackles.TeamAverage, type = "column") %>%
              hc_add_series(name = "Competition Average", data = target$Tackles.CompetitionAverage, type = "column") %>%
              hc_add_series(name = "Position Average", data = target$Tackles.CompetitionAverage.Position, type = "column") %>%
                  hc_tooltip(sort = TRUE, table = TRUE, valueDecimals = 2, type = "column") %>%
                  hc_colors(cols) %>%
                          hc_title(text = "Total Average Tackles per game")

# %>%
#   hc_tooltip(sort = TRUE, table = TRUE, valueDecimals = 2) %>%
#   hc_yAxis(min = 0, max = 1) %>%
#   hc_colors(cols)


})

pt6
```


</div>
</div>